# Generated by Django 4.2.7 on 2023-12-03 00:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['title', 'status'],
            },
        ),
        migrations.CreateModel(
            name='MyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 3, 3, 45, 0, 791569), verbose_name='Дата создания')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('anouncement', models.TextField(help_text='это аннотация', max_length=256, verbose_name='Аннотация')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('dt_public', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[('E', 'Economics'), ('S', 'Science'), ('IT', 'IT'), ('F', 'Fails')], max_length=20, verbose_name='Категории')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(blank=True, to='my_news.mytag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-dt_public', 'title'],
            },
        ),
    ]
