# Generated by Django 4.2.7 on 2023-12-04 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='dt_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 5, 1, 39, 20, 186279), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='myarticle',
            name='dt_public',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 1, 39, 20, 186279), verbose_name='Дата публикации'),
        ),
    ]
