# Generated by Django 4.2.7 on 2023-12-11 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0004_alter_myarticle_dt_create_alter_myarticle_dt_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='category',
            field=models.CharField(choices=[('hot', 'Горячее'), ('fresh', 'Свежее'), ('subscription', 'Лучшее')], max_length=20, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='myarticle',
            name='dt_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 11, 12, 51, 38, 532666), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='myarticle',
            name='dt_public',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 12, 51, 38, 532666), verbose_name='Дата публикации'),
        ),
    ]
