# Generated by Django 4.2.7 on 2023-12-12 00:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0005_alter_myarticle_category_alter_myarticle_dt_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='dt_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 12, 3, 21, 20, 752745), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='myarticle',
            name='dt_public',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 3, 21, 20, 752745), verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='article_image/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_news.myarticle')),
            ],
        ),
    ]
