# Generated by Django 4.2.7 on 2023-12-15 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0006_alter_myarticle_dt_create_alter_myarticle_dt_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='category',
            field=models.CharField(choices=[('hot', 'Горячее'), ('fresh', 'Свежее'), ('best', 'Лучшее')], max_length=20, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='myarticle',
            name='dt_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 15, 3, 33, 38, 812181), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='myarticle',
            name='dt_public',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 3, 33, 38, 812181), verbose_name='Дата публикации'),
        ),
    ]
