# Generated by Django 4.2.7 on 2023-12-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0007_alter_myarticle_category_alter_myarticle_dt_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarticle',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='myarticle',
            name='dt_public',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
