# Generated by Django 4.2.7 on 2023-12-04 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_dt_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dt_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 5, 1, 40, 26, 903221), verbose_name='Дата создания'),
        ),
    ]
