# Generated by Django 4.2.7 on 2023-12-06 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_article_slug_alter_article_dt_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='dt_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 6, 11, 27, 46, 478743), verbose_name='Дата создания'),
        ),
    ]
