# Generated by Django 4.2.7 on 2023-12-06 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_article_slug_alter_article_dt_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dt_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 6, 16, 49, 1, 987375), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='article_image/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
            ],
        ),
    ]
