# Generated by Django 4.2.7 on 2023-12-15 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_article_dt_create_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dt_create',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 15, 3, 33, 38, 813178), verbose_name='Дата создания'),
        ),
    ]
