# Generated by Django 4.2.7 on 2023-12-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_article_dt_create_alter_article_dt_public_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcount',
            options={'ordering': ('-dt_view',)},
        ),
        migrations.RemoveIndex(
            model_name='viewcount',
            name='news_viewco_view_da_c81d57_idx',
        ),
        migrations.RenameField(
            model_name='viewcount',
            old_name='view_date',
            new_name='dt_view',
        ),
        migrations.AlterField(
            model_name='article',
            name='dt_public',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['-dt_view'], name='news_viewco_dt_view_3844c0_idx'),
        ),
    ]
